### ISSUE TITLE
Failing to retrieve evm.js reconstructed source code

### ISSUE THREAD

**Issue by KadenZipfel** [ConsenSys/vscode-ethover#2]
Selecting evm.js from the hover options results in no contract code being returned. Instead, it seems to hang and load indefinitely.

Windows 10.0.18363
VSCode 1.47.2

**Comment by tintinweb** [comment]
Hey @KadenZipfel, can you provide the address you tried it on?

Cheers,
tin

PS: that method is a bit experimental :) probably should have noted it 😂

**Comment by KadenZipfel** [comment]
It was on this address `0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643`
