### ISSUE TITLE
support for bsc/other eth-like chains?

### ISSUE THREAD

**Issue by wizzard0** [ConsenSys/vscode-ethover#6]
works to some extent already by changing block explorer address, but would be nice to be able to work with multiple chains too

**Comment by nnnnicholas** [comment]
+1 for general evm support. Rinkeby and Polygon come to mind.

**Comment by tintinweb** [comment]
Hi @wizzard0, @nnicknelsonn,

how would you imagine this to be used? can you mock this somehow and I'll take a look at how much effort it would be to implement it?

cheers

**Comment by nnnnicholas** [comment]
One approach would be to have the extension check a user-modifiable list of chains.
![image](https://user-images.githubusercontent.com/1418561/129434828-3667f817-8cc6-4c96-873d-d036de77e5dc.png)

On hover, the extension could query all chains selected in the settings menu, then populate the parenthetical list with those chains where the address has activity. When the user clicks a given network inside the parentheses, the Eth balance and links update to the match the selected chain.
![image](https://user-images.githubusercontent.com/1418561/129434659-36ef668d-0dc6-4a84-828a-d5ed529388a7.png)

**Comment by tintinweb** [comment]
Hey @wizzard0 @nnnnicholas,

allow custom chain configs with #8. Show's sum of all "fetchable" balances. This should close this issue.

cheers

![image](https://user-images.githubusercontent.com/2865694/143015504-fbfea586-4baa-44a7-84c3-dbf8a988838c.png)
